
--CRIAR O BANCO DE DADOS --
CREATE DATABASE salvaCEP;

--SELECIONAR QUAL BANCO IRA USAR--
USE salvaCEP;

--CRIAR TABELA PARA SALVAR & CONSULTAR CEP--
CREATE TABLE tb_cep (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	cep VARCHAR (9),
	logradouro VARCHAR (50),
    bairro VARCHAR (50),
    localidade VARCHAR(50),
    uf VARCHAR (2)
);  